import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "./components/MainLayout";
import WrapperContextClient from "./utility/GlobalContext/MyContext";
import HeadTitle from "./utility/HeadTitle/HeadTitle";
import LoadingPage from "./components/loadingPage/LoadingPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://erlanggaht93.vercel.app/assets/ghost-halloween-horror-svgrepo-com-74d2419c.svg"
        />
        <HeadTitle/>
        </head>
      <WrapperContextClient>
        <body className={inter.className}>
           <LoadingPage/>
          <MainLayout>{children}</MainLayout>
        </body>
      </WrapperContextClient>
    </html>
  );
}
