#!/usr/bin/bash

source .env
DEFAULT_HOST=0.0.0.0
DEFAULT_PORT=3000
DEFAULT_BACKEND_PORT=4001

EXE_HOST=${HOST:-$DEFAULT_HOST}
EXE_PORT=${PORT:-$DEFAULT_PORT}
EXE_BACKEND_PORT=${BACKEND_PORT:-$DEFAULT_BACKEND_PORT}

npx next dev -- -H $EXE_HOST -p $EXE_PORT
